# Generated by Django 3.1 on 2022-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsletterrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
